name: Sign and Release

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Get Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Update version.properties file

      - name: Update app version
        run: |
          code_old=$((grep -w VERSION_CODE | cut -d= -f2) < app/version.properties)
          code=$(($code_old + 1))
          sed -i "s/VERSION_CODE=${code_old}/VERSION_CODE=${code}/g" app/version.properties
          name=$(sed -n '1p' app/version.properties)
          sed -i "s/${name}/VERSION_NAME=${RELEASE_VERSION}/g" app/version.properties
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Bumb app version to ${RELEASE_VERSION}"

      # Build the APK

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      # Sign the AAB

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # Upload the AAB to GitHub and Play Store

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: BableSchool_${{ env.RELEASE_VERSION }}
          path: ${{ env.SIGNED_RELEASE_FILE }}

      - name: Upload tha APK to the Release on Github
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_VERSION }}
          files: ${{ env.SIGNED_RELEASE_FILE }}
          allow_override: true
          gzip: false

      # Push version.properties file changes

      - name: Push changes
        run: git push